### Site info:
title:"Dev blog"
author:"Phil Head"
email:"phil@schoolcomms.co.uk"
baseurl:""
url:""


### Personal info and site tools info:
twitter_username:""
github_username:"philcomms"
disqus_shortname:""
favicon:""
aboutme:""
aboutme_photo:""


### Site setting:
ShowContactInfo:"False" # Personal Info (twitter,github,email) can be seen on aboutme-sidebar, those info only shown where ShowContactInfo == True
default_column:"two" # blog style: two columns, if default_column != "two", you will see a one column blog.
default_locale:"en" # blog sidebar language set, only include: English(en) and Chinese (cn)


    en:
      Aboutme: "About Me"
      Archives: "Archives"
      Blogroll: "Blogroll"
      Categories: "Categories"
      Copyright_Notice: "Copyright Notice"
      Recent_Posts: "Recent Posts"
      Tags: "Tags"
      Previous: "Older"
      Next: "Newer"
      PostedInCategories: "Posted in"
      Taggedwith: "and tagged"  
      PostDate: "on "
    cn:
      Aboutme: "关于我"
      Archives: "存档"
      Blogroll: "良师益友"        
      Categories: "分类目录"    
      Copyright_Notice: "版权声明"
      Recent_Posts: "近期文章"
      Tags: "标签" 
      Previous: "前一页"
      Next: "后一页"
      PostedInCategories: "目录:"   
      Taggedwith: "| 标签:"
      PostDate: "| 发表时间: "


### your Blogroll info, only name can shown on the page.

Blogroll:""

### Build settings
markdown: redcarpet
highlighter: pygments
paginate: 5
