# Site settings
title: Dev Blog
email: phil@schoolcomms.co.uk
description: > # this means to ignore newlines until "baseurl:"
 
baseurl: "" 
url: ""


# Build settings
markdown: redcarpet
highlighter: pygments
